### ISSUE TITLE
Problem Building Daemon for OpenWrt

### ISSUE THREAD

**Issue by hogkite** [ipilcher/fdf#3]
Hi Ian,

Great documentation btw! I thought I would have a go at building fdf for my OpenWrt device. I've had to start from scratch and build the whole toolchain for OpenWrt etc. Anyway the initial setup worked fine and I can now build new images for OpenWrt. I then started to look at buiding fdf....this isn't something I do everyday so bear with me,I've been taking it step by step. I ran into a couple of issues with certain things not quite working and worked my way around them ok.

However, in section 3c for building the daemon I keep getting errors about the STAGING_DIR not being defined, I don't recall this being one of the variables that needed setting? When I try to build the daemon these are the errors I'm getting...

~/openwrt/fdf/src$ $XGCC -O3 -Wall -Wextra -Wcast-align -o fdfd -I${HEADER_DIR} *.c \
> -L${LIB_DIR} -lsavl -ljson-c -ldl -Wl,--dynamic-list=symlist
mipsel-openwrt-linux-musl-gcc: warning: environment variable 'STAGING_DIR' not defined
mipsel-openwrt-linux-musl-gcc: warning: environment variable 'STAGING_DIR' not defined
mipsel-openwrt-linux-musl-gcc: warning: environment variable 'STAGING_DIR' not defined
mipsel-openwrt-linux-musl-gcc: warning: environment variable 'STAGING_DIR' not defined
mipsel-openwrt-linux-musl-gcc: warning: environment variable 'STAGING_DIR' not defined
mipsel-openwrt-linux-musl-gcc: warning: environment variable 'STAGING_DIR' not defined
mipsel-openwrt-linux-musl-gcc: warning: environment variable 'STAGING_DIR' not defined
mipsel-openwrt-linux-musl-gcc: warning: environment variable 'STAGING_DIR' not defined
mipsel-openwrt-linux-musl-gcc: warning: environment variable 'STAGING_DIR' not defined
mipsel-openwrt-linux-musl-gcc: warning: environment variable 'STAGING_DIR' not defined
mipsel-openwrt-linux-musl-gcc: warning: environment variable 'STAGING_DIR' not defined
/home/mike/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: /tmp/ccDexE7a.o: in function `fdf_get_filter':
filter.c:(.text+0x1d8): undefined reference to `savl_get'
/home/mike/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: filter.c:(.text+0x1ec): undefined reference to `savl_get'
/home/mike/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: /tmp/ccDexE7a.o: in function `fdf_filter_add_current':
filter.c:(.text+0x240): undefined reference to `savl_try_add'
/home/mike/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: filter.c:(.text+0x284): undefined reference to `savl_try_add'
/home/mike/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: /tmp/ccDexE7a.o: in function `fdf_free_filters':
filter.c:(.text+0x2c8): undefined reference to `savl_free'
/home/mike/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: /tmp/ccDexE7a.o: in function `fdf_load_filter':
filter.c:(.text+0x4d0): undefined reference to `savl_get'
/home/mike/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: /tmp/ccyA1AV9.o: in function `fdf_free_match':
match.c:(.text+0x19c): undefined reference to `savl_remove_node'
/home/mike/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: match.c:(.text+0x1cc): undefined reference to `savl_remove_node'
/home/mike/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: /tmp/ccyA1AV9.o: in function `fdf_try_add_match':
match.c:(.text+0x200): undefined reference to `savl_try_add'
/home/mike/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: match.c:(.text+0x234): undefined reference to `savl_try_add'
/home/mike/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: /tmp/ccyA1AV9.o: in function `fdf_get_match':
match.c:(.text+0x280): undefined reference to `savl_get'
/home/mike/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: match.c:(.text+0x294): undefined reference to `savl_get'
/home/mike/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: /tmp/ccyA1AV9.o: in function `fdf_free_matches':
match.c:(.text+0x2c4): undefined reference to `savl_free'
/home/mike/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: /tmp/cc7NO1N9.o: in function `fdf_get_netif':
netif.c:(.text+0x60): undefined reference to `savl_get'
/home/mike/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: netif.c:(.text+0x74): undefined reference to `savl_get'
/home/mike/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: netif.c:(.text+0x17c): undefined reference to `savl_try_add'
/home/mike/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: netif.c:(.text+0x1c8): undefined reference to `savl_try_add'
/home/mike/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: /tmp/cc7NO1N9.o: in function `fdf_free_netifs':
netif.c:(.text+0x260): undefined reference to `savl_free'
collect2: error: ld returned 1 exit status

If this is just a case of defining the variable (if so, could you tell me the path please) or is there more to it? Thanks Mike

**Comment by ipilcher** [comment]
Mike -

Nice to hear to that someone is giving this a shot, and congratulations on finding the very first documentation bug!

That's a bug in documentation.  I forgot about setting that variable.

For your reference, that variable is covered in the OpenWrt cross compiling documentation [here](https://openwrt.org/docs/guide-developer/toolchain/crosscompile), but I think that it should be the value of `${TOOLCHAIN_DIR}` without the `/bin` on the end.

Or to put it the opposite way,

```
TOOLCHAIN_DIR=${STAGING_DIR}/bin
```

You'll need to export it as well.

However, it looks to me as if that's just a warning, since it seems to get to the linking phase, where it gives you a bunch of "undefined reference" errors.  I'm guessing that you skipped one or more of the `libsavl`-related steps in step 3b.

Let me know how it goes.

Thanks!

**Comment by hogkite** [comment]
Ian,

Thanks, as soon as I sorted out the STAGING_DIR variable it all worked correctly. I'll do the install to OpenWrt later today but just on documentation I'm not sure the setting of the HEADER_DIR in section 3a is correct, at least it didn't work quite as described for me........

The following didn't work....

HEADER_DIR=`echo ${LIB_DIR} | sed 's/lib$/include/'`

Is this because LIB_DIR is already pointing to /usr/lib and HEADER_DIR needs to point to /usr/include not /usr/lib/include?

The only other thing I had to change was my path to BASH in the shell script which I guess is specific to my system.

Great work!

**Comment by ipilcher** [comment]
> Thanks, as soon as I sorted out the STAGING_DIR variable it all worked correctly.

Weird.  I just ran through steps 1-3 again, without setting `STAGING_DIR`.  I did get a bunch of warnings about it, but everything still built just fine.  (I'm still going to update the doc to cover setting it.)

> The following didn't work....  
> 
> HEADER_DIR=`echo ${LIB_DIR} | sed 's/lib$/include/'`
> 
> Is this because LIB_DIR is already pointing to /usr/lib and HEADER_DIR needs to point to /usr/include not /usr/lib/include?

That's working here.  That `sed` command matches the `lib` at the end of its input (which is the value of `LIB_DIR`) and replaces it with `include`.  For example:

```
$ echo $LIB_DIR
/mnt/scratch/openwrt/staging_dir/target-mips_24kc_musl/usr/lib

$ echo $LIB_DIR | sed 's/lib$/include/'
/mnt/scratch/openwrt/staging_dir/target-mips_24kc_musl/usr/include

$ HEADER_DIR=`echo $LIB_DIR | sed 's/lib$/include/'`
/mnt/scratch/openwrt/staging_dir/target-mips_24kc_musl/usr/include
```

> The only other thing I had to change was my path to BASH in the shell script which I guess is specific to my system.

Am I correct in thinking that you're referring to the `apiver.sh` shell script and your distribution has bash at `/bin/bash` (rather than `/usr/bin/bash`)?

Glad to hear that you got it built!

**Comment by hogkite** [comment]
Thanks Ian,

The sed command didn't seem to work for me so I just adjusted it manually. Yes I am referring to the apiver,.sh script and correct re. bash path.

It's all installed now on my OpenWrt router, just need to look into the config in more detail and get it all set up.

Shall I close this issue?

**Comment by ipilcher** [comment]
> Shall I close this issue?

Not yet.  If it's OK with you, I'd like to have you review the instructions once I've updated them to include setting the `STAGING_DIR` variable.

**Comment by hogkite** [comment]
Yes no problem, let me know when you've updated them

**Comment by ipilcher** [comment]
All done.  Let me know what you think.

Since I need to have `STAGING_DIR` set anyway, I got rid of the `TOOLCHAIN_DIR` variable; it's easy enough to just use `${STAGING_DIR}/bin`.

**Comment by hogkite** [comment]
I ran through it again and all works perfectly. In addition to your instructions I did also set the PATH and exported it as you referred to previously just in case it was likely to cause any issues during compilation. I think the only other thing to perhaps mention is that when you describe setting the build directory I assumed that means "openwrt" and not "openwrt/build_dir" which is what you might think if you read the openwrt article on directory structures?

**Comment by ipilcher** [comment]
Thanks for taking the time to go through it.  I've added a note to the documentation about the difference between `BUILD_DIR` and `build_dir` (although I'm not whether it makes things clearer or more confusing).

Now that you've got it built, were you able to get FDF configured and working?

**Comment by hogkite** [comment]
I've not had chance yet to configure it........I need to get my head around the config instructions and then set it up.  I've got fairly basic requirements to start with just passing multicast from my UPnP server and my Roon core to another subnet, in total 3 different multicast addresses (I currently use smcroute to achieve this).  Will also look at mDNS for possible Chrome Audio usage. I'll let you know how it goes as soon as I get chance.

**Comment by hogkite** [comment]
Not had much success getting this working on OpenWrt so far. I have 2 LAN ports in in one bridge group "br-lan" and another 2 LAN ports in a second bridge group "br-lan2" (two different subnets). Each has it's own firewall zone. I have used the bridge interface definitions within the fdf-config.json file, I'm assuming this is ok. I've also allowed within the firewall definition for the required multicasts to be passed between the firewall zones. I've also increased the TTL of the multicast packets via iptables commands.

I don't see any multicast traffic being received into the relevant zone whatsoever.  FDFD is running although I can't seem to start it with the command line options.  I get the standard service options for FDFD e.g start,stop, restart etc etc. Here is the json file...any thoughts?

```
{
  "matches": {
    "ssdp": {
      "addr": "239.255.255.250",
      "port": 1900
    },
    "roon2": {
      "addr": "239.255.255.249",
      "port": 9003
    },
    "roon3": {
      "addr": "239.255.90.90",
      "port": 9003
    }
  },
  "listen": {
    "br-lan": {
      "ssdp": ["br-lan2"],
      "roon2": ["br-lan2"],
      "roon3": ["br-lan2"]
    },
    "br-lan2": {
      "ssdp": ["br-lan"],
      "roon2": ["br-lan"],
      "roon3": ["br-lan"]
    }
  }
}
```

**Comment by ipilcher** [comment]
First, please format the config JSON in a fixed-width font, so that it's actually readable.

>  I have used the bridge interface definitions within the fdf-config.json file, I'm assuming this is ok

Assuming that the bridges have the IP addresses assigned to them, then this is correct.  (I.e., `ifconfig br-lan` and `ifconfig br-lan2` should show the IP addresses that the router uses in those subnets.

> I've also allowed within the firewall definition for the required multicasts to be passed between the firewall zones. I've also increased the TTL of the multicast packets via iptables commands.

I can only speak conceptually about the firewall settings, because I don't use the normal OpenWrt firewall, but ... Did you allow the multicast traffic to be **routed** between zones?  That would be the correct thing to to, if you were configuring multicast routing, but that's not what FDF does.  You need to enable FDF (running on the router) to **receive** those multicast packets, so that it can turn around and re-send them on the other interface.

For example, if your were using old-school `iptables`, you would need to modify the `INPUT` chain, not the `FORWARD` chain.  (And because FDF is re-sending the packets, rather than routing them, you don't need to mess around with the TTL.)

> FDFD is running although I can't seem to start it with the command line options. I get the standard service options for FDFD e.g start,stop, restart etc etc. 

How are you trying to run `fdfd`?  Assuming that it's in your `PATH` you should be able to simply run it.  For example:

```
# fdfd -h
fdfd options:
    -l | --syslog:  log messages to syslog
    -e | --stderr:  log messages to stderr
    -d | --debug: log debug level messages
    -p | --pktlog: enable verbose packet logging
    -c | --config: specify configuration file
    -h | --help: show this message and exit
```

It sounds like you're running the service script (`/etc/init.d/fdfd`), rather than the executable (`/usr/bin/fdfd`).  `/etc/init.d` should **not** be in your `PATH`.

HTH

**Comment by hogkite** [comment]
Thanks Ian

> First, please format the config JSON in a fixed-width font, so that it's actually

I've updated my original post

> Did you allow the multicast traffic to be routed between zones? That would be the correct thing to to, if you were configuring multicast routing, but that's not what FDF does. You need to enable FDF (running on the router) to receive those multicast packets, so that it can turn around and re-send them on the other interface.

Yes I did.........so do I need to remove those rules and replace with something else? Just re-read your instructions and I'm not entirely clear on exactly what to do?

> For example, if your were using old-school iptables, you would need to modify the INPUT chain, not the FORWARD chain. (And because FDF is re-sending the packets, rather than routing them, you don't need to mess around with the TTL.)`

I did modify the PREROUTING table to adjust TTL but have now removed those iptables rules 

> How are you trying to run fdfd? Assuming that it's in your PATH you should be able to simply run it.`

/usr/bin is definitely in my PATH. /etc/init.d is definitely NOT in my PATH but I still get the service options when running fdfd -h from within /usr/bin

Strange?

**Comment by ipilcher** [comment]
> > First, please format the config JSON in a fixed-width font, so that it's actually
> 
> I've updated my original post

Thanks.  I can see that you've defined 3 protocols &mdash;  `ssdp`, `roon2`, and `roon3` &mdash; and your forwarding all of them in both directions &mdash; from `br-lan` to `br-lan2` and vice versa.  There's nothing wrong with doing that, but it probably isn't what you want, unless you have both "discoverers" (usually clients) and "discoverees" (usually servers) on both networks.

Taking SSDP (which is the only one of the protocols with which I am familiar), on which network(s) is/are your media server(s) located &mdash; `br-lan`, `br-lan2`, or both?  Ignoring mDNS for the moment, you generally only need to forward discovery packets from the discoverer/client network to the discoveree/server network.  The servers will send **unicast** responses back to the clients, which are routed by normal means.

> Yes I did.........so do I need to remove those rules and replace with something else? Just re-read your instructions and I'm not entirely clear on exactly what to do?

Correct, and this is the part where I can only speak theoretically, because I don't use the OpenWrt firewall.  `fdfd` will be an application running on the OpenWrt device, so you need to open the relevant ports in the input, not forwarding, configuration of your firewall.  Your OpenWrt firewall presumably has rules that allow incoming HTTP/HTTPS and SSH connections on certain interfaces/networks, so you may be able to use those as templates (but remember to add the correct multicast or broadcast IP address to the rules as the **destination**).

> /usr/bin is definitely in my PATH. /etc/init.d is definitely NOT in my PATH but I still get the service options when running fdfd -h from within /usr/bin

It sounds like you may have accidentally copied the script into `/usr/bin`, rather than the binary.  What does `head -n1 /usr/bin/fdfd` say?  (It should give you a bunch of garbage characters.)

**Comment by hogkite** [comment]
I've set up a test rig for this so unfortunately I don't have all my media servers connected. On my main rig I do have a SSDP server and a Roon server (Audio server) set up on what would be equivalent to "br-lan2". My clients are all on the equivalent of "br-lan". On the test rig I only have my Roon server connected and a client. The client side of Roon also sends multicasts which is why I set it up to bi-directional, appreciate I may not need this for SSDP.

I'm still not 100% on the firewall but I'll come back to that later.

Yes stop on re. the binary. Not sure whether it's my set up or an error with the procedure.....when the instructions refer to the scp part it copies 2 files called fdfd (the binary and the script). My screenshot is the same as yours. However, on closer inspection on openwrt only one fdfd file exists and that is the script, so consequently yes I have copied the script into /usr/bin (did the script overwrite the binary?)

I've fixed it now by manually copying the binary across into usr/bin. At step 4e am I correct in assuming it's the script to be copied into /etc/init.d/?

I've got to go out for a couple of hours but I'll do some more testing when I get back and look again at the firewall side.

**Comment by ipilcher** [comment]
> Yes stop on re. the binary. Not sure whether it's my set up or an error with the procedure.....when the instructions refer to the scp part it copies 2 files called fdfd (the binary and the script).

That's a bug in the instructions.  Thanks for spotting that!

**Comment by hogkite** [comment]
It all seems to be working!!

I get what you are saying about the different firewall chains but I suspect this is taken care of by the firewall config GUI that has been built for OpenWrt. Whilst I can add custom rules using iptables commands such as mangling the ttl (if required) the basic config is controlled through a GUI where you specify what is allowed to pass between zones. 

So I have left the multicast traffic rules in place (same as before) which is to say that multicast from a specific set of source addresses within the "br-lan2" zone with the relevant multicast destination address and port can flow to the "br-lan" zone. I allow  all traffic from "br-lan" to flow to "br-lan2".

**Comment by hogkite** [comment]
Ian,

Got a couple of queries for you please....

I assume I could just add libmnl via the package manager rather than add it at build time of OpenWrt if so desired?

If I build FDF from the OpenWrt toolchain created for 21.02.2 (or later even) is there any reason why those FDF components wouldn't work on OpenWrt system running 21.02.1 or earlier (they do have different kernel versions)?

Thx

**Comment by ipilcher** [comment]
> I assume I could just add libmnl via the package manager rather than add it at build time of OpenWrt if so desired?

Absolutely.  That's the preferred way to install it on the target device.

But note that the library also has to be present in the build environment, so that you can build the IP set filter.  (If you don't want to use the IP set filter, you can skip `libmnl` entirely.)

> If I build FDF from the OpenWrt toolchain created for 21.02.2 (or later even) is there any reason why those FDF components wouldn't work on OpenWrt system running 21.02.1 or earlier (they do have different kernel versions)?

The kernel version shouldn't matter; it's the library versions that might bite you.  The easiest way to know is simply to try.  Alternatively, you can see what `ldd` says about the `fdfd` and filter binaries when you run it on the target device.

HTH
